<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Notification01</name>
   <tag></tag>
   <elementGuidId>261bae6b-3912-4a76-880f-9f6d437544eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/nav/div/div/div/ul/li[3]/ul/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>63ac2a16-9cbe-46a1-be5a-094ddbef590d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1700126608083</value>
      <webElementGuid>d98ce83e-5f8a-45ca-986a-944e814d7fa0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
