<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Previous</name>
   <tag></tag>
   <elementGuidId>e04c0d4a-18e9-4fe3-85a0-42ef6fcc8f21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.previous_page.disabled</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='products']/div[11]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>502ccd55-ee48-46a3-b5eb-72628870daa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>previous_page disabled</value>
      <webElementGuid>a70f7d72-3f21-4274-b5a5-1a4cadf2b195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93b5810f-1850-4e2d-a65c-a8649f4fa559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>← Previous</value>
      <webElementGuid>0faae6d3-03eb-44b4-b821-3ea3c1fa9311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products&quot;)/div[@class=&quot;d-flex gap-4 align-items-center justify-content-center my-5&quot;]/span[@class=&quot;previous_page disabled&quot;]</value>
      <webElementGuid>7d1c1464-b28f-4a25-96ca-c698a02eafa7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='products']/div[11]/span</value>
      <webElementGuid>36afb6a4-8e01-44f6-87b9-ae2b30ac4bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 787.878'])[1]/following::span[1]</value>
      <webElementGuid>adb1f255-dcb6-4b86-bf65-76a722927652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tes 01'])[1]/following::span[1]</value>
      <webElementGuid>c5857853-d4bd-403f-8dfc-e52a29972f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next →'])[1]/preceding::span[1]</value>
      <webElementGuid>4f3ca56a-8846-4b2a-9272-d1e95d91d076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jual'])[1]/preceding::span[1]</value>
      <webElementGuid>e6b110d2-108b-4d7c-9888-4a45d732af5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='← Previous']/parent::*</value>
      <webElementGuid>66f88ff9-03d4-4d37-a335-7a280c413d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/span</value>
      <webElementGuid>0146c038-ac36-42ea-8a2d-4052bb0c9a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '← Previous' or . = '← Previous')]</value>
      <webElementGuid>e37a5d32-a02b-4e39-9351-9577e407ad26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
