<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputfield_ImageProduk</name>
   <tag></tag>
   <elementGuidId>c0941f2e-72ab-44b6-89ba-1516d023d6ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'product[images][]' and @id = 'product_images']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;product_images&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>product[images][]</value>
      <webElementGuid>cd1f607c-7b0c-4048-89b8-d454215263a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product_images</value>
      <webElementGuid>de83a946-08c3-426c-b37b-ed9680c6287c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
